spring:
  application:
    name: spring-auth-service

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:auth_db;

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

jwt:
  secret: zRgmxBxzj3sFVzkivAfADSKMVskjF839nn9CZLEmvx4a
  access-token-expiration: 7200000
